package com.pa2.milk.api.model.enums;

public enum EnumAnalisesSolicitadas {
	COMPOSICAO, CASEINA, PONTO_CRIOSCOPICO, CELULAS_SOMATICAS,
	NITROGENIO_UREICO, CONDUTIVIDADE_ELETRICA, RESIDUO_ANTIBIOTICO, 
	ANALISES_FRAUDE, PH, SORO
}
